data:
  dataset_path: "datasets/ENB2012_data.xlsx"
  type: regression # Options: regression, classification
  # If columns are not valid Python identifiers, the program coonverts them,
  # and here you need to specify valid column
  # names (e.g. "Concrete compressive strength(MPa, megapascals)" -> "Concrete_compressive_strength_MPa_megapascals").
  target_columns:
    - Y1
    - Y2
  missing_value_strategy: 'drop'  # Options: 'mean', 'median', 'mode', 'drop'
  test_size: 0.2
  random_state: 42

selected_model: GeneticProgramming # Options: 'NeuralNetwork', 'GeneticProgramming'
loss_function: mae # Options: regression: 'mae', 'mse', 'r2', classification: 'accuracy', 'log_loss'

xai:
  # model filename must match dataset in data config
  model_filename_to_explain: "gp_model_Y2.pickle"
  model_target_column_name: "Y2"
  # Method options for both nn and gp: 'shap', 'lime', 'visualize', 'summarize'
  method: 'summarize'
  lime:
    index_instance_to_explain: [0, 1, 2] # List of indices in data to explain

logging:
  format: '%(message)s'
  level: "INFO"
  file: "logs/xai.log"
