data:
  dataset_path: "datasets/ENB2012_data.xlsx"
  type: regression # Options: regression, classification
  # If columns are not valid Python identifiers, the program coonverts them,
  # and here you need to specify valid column
  # names (e.g. "Concrete compressive strength(MPa, megapascals)" -> "Concrete_compressive_strength_MPa_megapascals").
  target_columns:
    - Y1
    - Y2
  missing_value_strategy: 'drop'  # Options: 'mean', 'median', 'mode', 'drop'
  test_size: 0.2
  random_state: 42

selected_model: NeuralNetwork # Options: 'NeuralNetwork', 'GeneticProgramming'
loss_function: r2 # Options: regression: 'mae', 'mse', 'r2', classification: 'accuracy', 'log_loss'

model_training:
  nn:
    # Neural Network Model
    hidden_units: 32
    hidden_layers: 3
    activation_function: relu
    batch_normalization: True
    learning_rate: 0.001
    optimizer: adam   # Options: 'adam', 'sgd'
    epochs: 200
    batch_size: 16
    dropout_rate: 0.0
    early_stopping: True
    reduce_loss: True
    tensorboard_cb: False
    print_train_logs: 1 # 0 - not printing, 1 - printing
  gp:
    # Genetic Programming Model
    population_size: 200
    generations: 50
    crossover_pb: 0.8
    mutation_pb: 0.2
    penalty_bloat: 0.00005
    elitism: True

logging:
  # format: '%(name)s - %(levelname)s - %(message)s'
  format: '%(message)s'
  level: "INFO"
  file: "logs/training.log"
