output_filename: "txtexpl.txt"
output_folder: "tmp"
model_type: "gp" # Options: 'nn' and 'gp'
shap:
  file: "tmp/gp_shap_values_Y1.npz"
  metadata_file: "tmp/gp_shap_metadata_Y1.json"
lime:
  file: "tmp/gp_lime_Y1_0.json"
summarization:
  file: "tmp/gp_summarize_Y1.json"
