output_filename: "txtexpl.txt"
output_folder: "tmp"
model_type: "nn" # Options: 'nn' and 'gp'
shap:
  file: "tmp/nn_shap_values_Y1.npz"
  metadata_file: "tmp/nn_shap_metadata_Y1.json"
lime:
  file: "tmp/nn_lime_Y1_0.json"
summarization:
  file: "tmp/nn_summarize_Y1.json"
